# Generated by Django 4.2.5 on 2023-09-30 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0006_advertisement_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='image',
        ),
    ]
